In [1]:
import numpy as np

print(np.__version__)

1.22.4


In [3]:
z = np.zeros((10))
print(z.shape)
print(z)

(10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(z.size)
print(z.itemsize)

10
8


In [5]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

In [6]:
z1 = np.zeros(10)
z1[4] = 1
print(z1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
r = np.arange(10, 50)
print(r)
r = r[::-1]
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
a = np.array([[1, 2, 3], [1, 2, 3]])
print(len(a))
print(a.shape[0])
print(np.amax(a[0]))

2
2
3


In [10]:
s = np.array([0.1, 0.2, 0.3, 0.4])
print(s)
s = np.reshape(s, (1, 4))
print(s)

np.amax([1, 2, 3])
np.average(s)

[0.1 0.2 0.3 0.4]
[[0.1 0.2 0.3 0.4]]


0.25

In [17]:
s = [[1,2,3,4,5,6]] * 6
s = np.reshape(s, (-1, 6, 6, 1))
s[0][5][0] = 10
print(s[0][5])

[[10]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]]


In [5]:
buffer = []
for i in range(10):
    buffer.append([i, (i+3)*2])

a = [b[1] for b in buffer]
a = np.array(a)
# a = a.reshape(-1, 1)
print(a[5])

16


In [2]:
ones = np.eye(10)[[2, 4, 1, 7, 6]]
print(ones)

rewards = [10, -8, 80, 26, -120]
p = ones * np.reshape(rewards, (len(rewards), 1))
print(p)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[[   0.    0.   10.    0.    0.    0.    0.    0.    0.    0.]
 [  -0.   -0.   -0.   -0.   -8.   -0.   -0.   -0.   -0.   -0.]
 [   0.   80.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.   26.    0.    0.]
 [  -0.   -0.   -0.   -0.   -0.   -0. -120.   -0.   -0.   -0.]]


In [3]:
drewards = np.zeros_like(rewards)
print(drewards)

[0 0 0 0 0]


In [3]:
mr = np.mean(rewards)
print(mr)

-2.4


In [7]:
a = np.array([1, 2, 3, 4, 5])
batch = [2, 4, 0]
a[batch]

array([3, 5, 1])