In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [ ]:
x = torch.ones(1)
w = torch.full([1], 2.)
w.requires_grad_()
print(x)
print(w)
print(w.grad)

In [ ]:
pred = torch.ones(1)
mse = F.mse_loss(pred, x*w)
print(mse)
torch.autograd.grad(mse, [w])

In [ ]:
mse = F.mse_loss(pred, x*w)
mse.backward()
print(w.grad)
print(w)

In [5]:
a = torch.tensor([1., 1., 1.])
a.shape
b = a.reshape((1, 3))
b.shape

c = b.view((1, 3, 1))
c.shape

torch.Size([1, 3, 1])

In [ ]:
from torch.distributions import Categorical

probs = torch.tensor([0.7, 0.12, 0.1, 0.08])
m = Categorical(probs)
counts = [0, 0, 0, 0]
for i in range(100):
    a = m.sample()
    counts[a.item()] += 1

print(counts)

In [5]:
layer = nn.Conv2d(1, 3, 5, 1, 2)
x = torch.rand(1, 1, 28, 28)
print(x.shape)
out = layer.forward(x)
print(out.shape)


torch.Size([1, 1, 28, 28])
torch.Size([1, 3, 28, 28])


In [ ]:
w = torch.rand(16, 3, 5, 5)
print(w.shape)
b = torch.rand(16)
print(b.shape)

x = torch.rand(1, 3, 28, 28)
out = F.conv2d(x, w, b, stride=1, padding=1)
print(out.shape)

In [2]:
a = torch.tensor([0.7, 0.2, 0.8, 1.6])
print(a.sum())
print(a.mean())

tensor(3.3000)
tensor(0.8250)


In [2]:
losses = []
losses.append(torch.Tensor([1., 1., 3.]))
losses.append(torch.Tensor([2., 3., 1.]))
losses = torch.cat(losses)
print(losses)

tensor([1., 1., 3., 2., 3., 1.])


In [3]:
t = torch.Tensor([[1.,2.,3.],[4.,3.,2.],[3.,3.,2.]])
print(t.mean())

tensor(2.5556)


In [3]:
a = torch.tensor(1)
print(a)

tensor(1)


In [6]:
mod = nn.Sequential(
    nn.Conv2d(3, 32, kernel_size=8, stride=4, padding=3),
    nn.ReLU(),
    nn.Conv2d(32, 64, kernel_size=4, stride=2, padding=1),
    nn.ReLU(),
    nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.Flatten()
)

print(mod)

x = torch.rand((2, 3, 16, 16))
y = mod(x)
print(y.shape)
print(y.shape[1])
action = F.softmax(y, dim=1)
print(action)

Sequential(
  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4), padding=(3, 3))
  (1): ReLU()
  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (3): ReLU()
  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (5): ReLU()
  (6): Flatten(start_dim=1, end_dim=-1)
)
torch.Size([2, 256])
256
tensor([[0.0039, 0.0040, 0.0039, 0.0040, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039,
         0.0040, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0042, 0.0041,
         0.0043, 0.0040, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039,
         0.0039, 0.0039, 0.0039, 0.0039, 0.0040, 0.0041, 0.0039, 0.0040, 0.0040,
         0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0040, 0.0040, 0.0039,
         0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039,
         0.0040, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039,
         0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0039, 0.0040, 0.0039,
         0.00

In [4]:
t = torch.tensor([[5]])
print(t)
x = t.squeeze(1)
print(x)

tensor([[5]])
tensor([5])
